# https://golangci-lint.run/usage/configuration/
# https://golangci-lint.run/usage/linters/#linters-configuration

run:
  tests: true
  build-tags: []
  skip-dirs: []

issues:
  max-same-issues: 0

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 5
    skip-tests: true

  errorlint:
    errorf: false
    errorf-multi: false
    asserts: false
    comparison: false

  exhaustruct:
    exclude:
      - 'http.Server'

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/p12s/go-service-template)
    custom-order: true

  gocognit:
    min-complexity: 30

  godox:
    keywords:
      - FIXME
      - TODO

  interfacebloat:
    max: 18

  funlen:
    lines: 60
    statements: 40

  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0666'
      - '0755'
      - '42'
    ignored-files:
      - 'excel.go$'
      - 'excel_test.go$'
    ignored-functions:
      - '^math\.'
      - '^http\.StatusText$'

  misspell:
    locale: US
    ignore-words:
      - some-word

  lll:
    line-length: 130
    tab-width: 1

  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: camel
        toml: snake

  varnamelen:
    max-distance: 6
    min-name-length: 2
    check-receiver: false
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - v
    ignore-decls:
      - c echo.Context
      - t testing.T
      - w http.ResponseWriter
      - r *http.Request
      - e error
      - i int

  wrapcheck:
    ignorePackageGlobs:
      - github.com/p12s/go-service-template/internal/service/*
      - github.com/p12s/go-service-template/internal/repository/*

linters:
  # disable-all: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - gosimple
    - govet
    - importas
    - interfacebloat
    - ineffassign
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - staticcheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

    # - nlreturn новая строка перед return не упрощает понимание
    # - goerr113 не обновлялся 3 года, нет настроек
    # - exhaustruct часто испольую инициализацию структур без полей, потому что читаемость не ухудшает, а кода меньше
    # - dupl нет настроек, чтобы не проверялись тесты - там много дупликаций
    # - tagalign выравнивать теги нет необходимости
